---
- name: Set up server
  become: true
  block:
  - name: Add authorized key
    ansible.posix.authorized_key:
      user: "{{ DEPLOY_USER }}"
      state: present
      key: "{{ lookup('file', '/home/red/.ssh/id_rsa.pub') }}"

  - name: Install packages
    ansible.builtin.apt: name={{ item }} state=latest update_cache=true
    with_items:
      - build-essential
      - cewl
      - chromium
      - curl
      - dirb
      - fcrackzip
      - ffuf
      - fonts-powerline
      - gdb
      - git
      - gobuster
      - hashcat
      - hydra
      - jq
      - john
      - libffi-dev
      - libssl-dev
      - neofetch
      - nikto
      - nmap
      - nodejs
      - openjdk-11-jdk
      - openssh-client
      - openvpn
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - rdesktop
      - ruby
      - sqlmap
      - smbclient
      - smbmap
      - sudo
      - tcpdump
      - traceroute
      - ufw
      - vim
      - wfuzz
      - wget
      - whatweb
      - whois
      - wireshark
      - zsh

  - name: Enable SSH over firewall
    community.general.ufw:
      rule: allow
      name: "OpenSSH"

  - name: Set up UFW firewall
    community.general.ufw:
      state: enabled
      policy: deny 
